/** Uvas semilla (~30). Las que faltan se crean al vuelo al cargar un vino. */
export const SEED_GRAPES = [
  'Malbec',
  'Cabernet Sauvignon',
  'Cabernet Franc',
  'Merlot',
  'Bonarda',
  'Syrah',
  'Pinot Noir',
  'Tannat',
  'Tempranillo',
  'Petit Verdot',
  'Chardonnay',
  'Sauvignon Blanc',
  'Torrontés',
  'Semillón',
  'Viognier',
  'Chenin Blanc',
  'Riesling',
  'Pinot Grigio',
  'Moscatel',
  'Criolla',
  'Pedro Giménez',
  'Ancellotta',
  'Garnacha',
  'Sangiovese',
  'Nebbiolo',
  'Barbera',
  'Carménère',
  'País',
  'Verdejo',
  'Albariño',
] as const;
